version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - db-volume:/usr/src/app/data
    # env_file:
    #   - ./api/.env

volumes:
  db-volume: